### ISSUE TITLE
Thank you for generously sharing the code. 

### ISSUE THREAD

**Issue by wuming803** [Sam1224/P2CNet#1]

**Comment by li-huang912** [comment]
I have attempted to run it on two different datasets, but unfortunately, the models did not converge successfully. The  IOU results were  low. I noticed that I used a batch size of 1, and I’m wondering if this might have any impact on the results. Would it be possible for you to kindly provide some insight into the training parameters you used?

**Comment by wuming803** [comment]
I have attempted to run it on two different datasets, but unfortunately, the models did not converge successfully. The  IOU results were  low. I noticed that I used a batch size of 1, and I’m wondering if this might have any impact on the results. Would it be possible for you to kindly provide some insight into the training parameters you used?
